stages:
  - build
  - deploy

variables:
  IMAGE: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}-${CI_COMMIT_BRANCH}"
  IMAGE_LATEST: "$CI_REGISTRY_IMAGE:swarm"


build-dev:
  stage: build
  before_script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
  script:
    - docker build -t $IMAGE -t $IMAGE_LATEST -f Dockerfile.prod  .
    - docker push $IMAGE_LATEST
    - docker push $IMAGE
  tags:
    - swarm

.deploy:
  stage: deploy
  script: 
    - echo "$AI_CHAT" > ai_chat
    - echo "$CHAT_DATABASE" > database
    - docker stack deploy -c docker-compose.yml muul --with-registry-auth
    # - docker image prune -af
  tags:
    - swarm

deploy-swarm:
  environment: prod
  extends: .deploy
