# docker-compose.yml
version: '3.8' 

services:

  web:
    build: .
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env

  redis:
    image: redis/redis-stack:latest 
    ports:
      - "6379:6379"
  
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
    volumes:
      - redisinsight_data:/db

  database:
    image: postgres
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
    ports:
    - "5900:5900"

volumes:
  db_data:
  redisinsight_data: