# /home/irina/a_rubytut/docker_ror/planta_chat/docker-compose.yml
version: '3.8' 

services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    networks:
      - shared_network

  redis_web:
    image: redis/redis-stack:latest 
    ports:
      - "6379:6379"
    networks:
      - shared_network
  
  redisinsight_web:
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
    volumes:
      - redisinsight_data_web:/db

  database_web:
    image: postgres
    env_file:
      - .env
    volumes:
      - db_data_web:/var/lib/postgresql/data
    networks:
      - shared_network

  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
    ports:
    - "5900:5900"
    networks:
    - shared_network

volumes:
  db_data_web:
  redisinsight_data_web:

networks:
  shared_network:
    external: true