version: '3.8'

services:

  ai_chat:
    image: $CI_REGISTRY_IMAGE:dev
    container_name: ai_chat
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    env_file:
      - /opt/env/development/database
      - /opt/env/development/ai_chat
    depends_on: 
      - ai_chat_db
      - ai_chat_redis
    networks:
      - ai_chat_back
      - chat_bot

  ai_chat_redis:
    image: redis/redis-stack:7.2.0-v4
    networks:
      - ai_chat_back

  ai_chat_redis_uploader:
    image: $CI_REGISTRY_IMAGE:dev
    # image: infrastructure-ai_chat
    container_name: ai_chat_redis_uploader
    command: ["./wait-for", "--timeout=60", "ai_chat_redis:6379", "--",
      "ruby", "bin/redis_uploader.rb"]
    env_file:
      - /opt/env/development/database
      - /opt/env/development/ai_chat
    networks:
      - ai_chat_back
    deploy:
      restart_policy:
        condition: none

  ai_chat_db_migrator:
    image: $CI_REGISTRY_IMAGE:dev
    # image: infrastructure-ai_chat 
    container_name: ai_chat_db_migrator
    command: ["./wait-for", "--timeout=60", "ai_chat_db:5432", "--",
      "bin/rails", "db:prepare"]
    env_file:
      - /opt/env/development/database
      - /opt/env/development/ai_chat
    networks:
      - ai_chat_back
    deploy:
      restart_policy:
        condition: none

  ai_chat_db:
    image: postgres
    container_name: ai_chat_db
    env_file:
      - ./env/development/database
    volumes:
      - db_data_ai_chat:/var/lib/postgresql/data
    networks:
      - ai_chat_back

  ai_chat_redisinsight:
    image: redislabs/redisinsight:1.14.0
    container_name:  ai_chat_redisinsight
    ports:
      - '8001:8001'
    volumes:
      - redisinsight_data_ai_chat:/db
    networks:
      - ai_chat_back

  selenium_chrome:
    image: selenium/standalone-chrome-debug:3.141.59
    container_name:  selenium_chrome
    logging:
      driver: none
    ports:
      - "5900:5900"
    networks:
      - ai_chat_back

volumes:
  db_data_ai_chat:
  redisinsight_data_ai_chat:

networks:
  ai_chat_back:
    driver: bridge
    name:   ai_chat_back
  chat_bot:
    driver: bridge
    name:   chat_bot