version: '3.8' 

services:

  web:
    image: irinalepekhina/menu_web:prod
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env

  redis:
    image: redis

  database:
    image: postgres
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: