version: '3.8'

services:

  ai_chat:
    image: $IMAGE
    container_name: ai_chat
    ports:
      - "3000"
      - "4000"
    env_file:
      - ./database
      - ./ai_chat
      - ./open_ai
    depends_on: 
      - ai_chat_db
      - ai_chat_redis
      
    networks:
      ai_chat_back:
        aliases:
          - ai_chat
      chat_bot:
        aliases:
          - ai_chat
      proxy_main:
        aliases:
          - ai_chat
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.muul_ai_chat.rule=Host(`chat.muul.ru`)"
        - "traefik.http.routers.muul_ai_chat.service=muul_ai_chat"
        - "traefik.http.routers.muul_ai_chat.tls.certresolver=le"
        - "traefik.http.routers.muul_ai_chat.entrypoints=websecure,web"
        - "traefik.http.services.muul_ai_chat.loadbalancer.server.port=3000"
        - "traefik.http.services.muul_ai_chat.loadbalancer.passhostheader=true"
  
  ai_chat_redis:
    image: redis/redis-stack:7.2.0-v4
    networks:
      ai_chat_back:
        aliases:
          - ai_chat_redis

  ai_chat_redis_uploader:
    image: $IMAGE
    container_name: ai_chat_redis_uploader
    command: ["./wait-for", "--timeout=60", "ai_chat_redis:6379", "--",
      "ruby", "bin/redis_uploader.rb"]
    env_file:
      - ./database
      - ./ai_chat
      - ./open_ai
    networks:
      ai_chat_back:
        aliases:
          - ai_chat_redis_uploader
    deploy:
      restart_policy:
        condition: none

  ai_chat_db_migrator:
    image: $IMAGE
    container_name: ai_chat_db_migrator
    command: ["./wait-for", "--timeout=60", "ai_chat_db:5432", "--",
      "bin/rails", "db:prepare"]
    env_file:
      - ./database
      - ./ai_chat
    networks:
      ai_chat_back:
        aliases:
          - ai_chat_db_migrator
    deploy:
      restart_policy:
        condition: none

  ai_chat_db:
    image: postgres:16
    container_name: ai_chat_db
    env_file:
      - ./database
    volumes:
      - db_data_ai_chat:/var/lib/postgresql/data
    networks:
      ai_chat_back:
        aliases:
          - ai_chat_db

volumes:
  db_data_ai_chat:

networks:
  ai_chat_back:
    driver: overlay
    name:   ai_chat_back
  chat_bot:
    driver: overlay
    name:   chat_bot
  proxy_main:
    external: true