version: '3.8' 

services:

  web:
    image: ghcr.io/irinalepekhina/planta_chat:dev
    build: .
    container_name: web
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    env_file:
      - ./env/development/database
      - ./env/development/web
    depends_on: 
      web_db:
        condition: service_started
    networks:
      - back
      - front

  web_redis:
    image: redis/redis-stack:latest
    container_name: web_redis
    ports:
      - "6379:6379"
    networks:
      - back

  web_db:
    image: postgres
    container_name: web_db
    env_file:
      - ./env/development/database
    volumes:
      - db_data_web:/var/lib/postgresql/data
    networks:
      - back

  web_db_migrator:
    image: ghcr.io/irinalepekhina/planta_chat:dev
    container_name: web_db_migrator
    command: ["./wait-for", "--timeout=60", "web_db:5432", "--",
      "bin/rails", "db:prepare"]
    env_file:
      - ./env/development/database
      - ./env/development/web
    networks:
      - back
    deploy:
      restart_policy:
        condition: none

  web_redis_uploader:
    image: ghcr.io/irinalepekhina/planta_chat:dev
    container_name: web_redis_uploader
    command: ["./wait-for", "--timeout=120", "web_redis:6379", "--",
      "ruby", "bin/redis_uploader.rb"]
    env_file:
      - ./env/development/database
      - ./env/development/web
    networks:
      - back
    deploy:
      restart_policy:
        condition: none

  web_redisinsight:
    image: redislabs/redisinsight:latest
    container_name:  web_redisinsight
    ports:
      - '8001:8001'
    volumes:
      - redisinsight_data_web:/db
    networks:
      - back

  selenium_chrome:
    image: selenium/standalone-chrome-debug
    container_name:  selenium_chrome
    logging:
      driver: none
    ports:
      - "5900:5900"
    networks:
      - back

volumes:
  db_data_web:
  redisinsight_data_web:

networks:
  front:
    driver: bridge
  back:
    driver: bridge