version: '3.8' 

services:

  web:
    image: ghcr.io/irinalepekhina/planta_chat:dev
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env

  redis:
    image: redis

  database:
    image: postgres
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
    ports:
    - "5900:5900"

volumes:
  db_data: